definitions:
  account.AccountBalanceResponse:
    properties:
      balance:
        description: Balance of the account.
        type: integer
      currency:
        description: Currency of the account.
        type: string
      id:
        description: ID of the account.
        type: string
    type: object
  account.CreateAccountRequest:
    properties:
      balance:
        description: |-
          Initial balance of the account.
          Example: 1000
        type: integer
      currency:
        description: |-
          Currency of the account. Allowed values: USD, EUR, GBP, JPY, EGP, CAD, AUD.
          Required: true
          Example: USD
        enum:
        - USD
        - EUR
        - GBP
        - JPY
        - EGP
        - CAD
        - AUD
        type: string
    required:
    - currency
    type: object
  account.CreateAccountResponse:
    properties:
      balance:
        description: |-
          Balance of the account.
          Example: 1000
        type: integer
      created_at:
        description: |-
          CreatedAt is the timestamp when the account was created.
          Example: "2023-10-01T12:00:00Z"
        type: string
      currency:
        description: |-
          Currency of the account.
          Example: USD
        type: string
      id:
        description: |-
          ID of the created account.
          Example: "123e4567-e89b-12d3-a456-426614174000"
        type: string
      owner:
        description: |-
          Owner of the account.
          Example: "John Doe"
        type: string
      user_id:
        description: |-
          UserID of the account owner.
          Example: "123e4567-e89b-12d3-a456-426614174001"
        type: string
    type: object
  account.model:
    properties:
      balance:
        type: integer
      created_at:
        type: string
      currency:
        type: string
      entries:
        description: Relationships
        items:
          $ref: '#/definitions/models.Entry'
        type: array
      id:
        type: string
      owner:
        type: string
      transfers_from:
        items:
          $ref: '#/definitions/models.Transfer'
        type: array
      transfers_to:
        items:
          $ref: '#/definitions/models.Transfer'
        type: array
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  models.Account:
    properties:
      balance:
        type: integer
      created_at:
        type: string
      currency:
        type: string
      entries:
        description: Relationships
        items:
          $ref: '#/definitions/models.Entry'
        type: array
      id:
        type: string
      owner:
        type: string
      transfers_from:
        items:
          $ref: '#/definitions/models.Transfer'
        type: array
      transfers_to:
        items:
          $ref: '#/definitions/models.Transfer'
        type: array
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  models.Entry:
    properties:
      account:
        $ref: '#/definitions/models.Account'
      accountID:
        type: string
      amount:
        type: integer
      createdAt:
        type: string
      id:
        type: string
    type: object
  models.Transfer:
    properties:
      amount:
        type: integer
      createdAt:
        type: string
      fromAccount:
        $ref: '#/definitions/models.Account'
      fromAccountID:
        type: string
      id:
        type: string
      toAccount:
        $ref: '#/definitions/models.Account'
      toAccountID:
        type: string
    type: object
  user.CreateUserRequest:
    description: Request payload for creating a new user.
    properties:
      email:
        description: |-
          Email address of the user. Must be a valid email format and unique.
          required: true
        type: string
      full_name:
        description: |-
          Full name of the user.
          required: true
        type: string
      password:
        description: |-
          Password for the new user. Minimum 6 characters.
          required: true
        minLength: 6
        type: string
      username:
        description: |-
          Username for the new user. Must be alphanumeric and unique.
          required: true
        type: string
    required:
    - email
    - full_name
    - password
    - username
    type: object
  user.LoginUserRequest:
    description: Request payload for logging in a user.
    properties:
      password:
        description: |-
          Password of the user
          required: true
        type: string
      username:
        description: |-
          Username of the user
          required: true
        type: string
    required:
    - password
    - username
    type: object
  user.LoginUserResponse:
    properties:
      access_token:
        description: |-
          Access token for the user
          required: true
        type: string
      user:
        description: |-
          User information
          required: true
        properties:
          email:
            description: |-
              Email of the user
              required: true
            type: string
          full_name:
            description: |-
              Full name of the user
              required: true
            type: string
          id:
            description: |-
              ID of the user
              required: true
            type: string
          username:
            description: |-
              Username of the user
              required: true
            type: string
        type: object
    type: object
  user.model:
    properties:
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /api/v1/account:
    post:
      parameters:
      - description: Account creation payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/account.CreateAccountRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/account.CreateAccountResponse'
      security:
      - JWT: []
      tags:
      - account
  /api/v1/account/{id}:
    get:
      parameters:
      - description: uuid of item
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.model'
      security:
      - JWT: []
      tags:
      - account
  /api/v1/account/{id}/balance:
    get:
      description: Returns the balance and currency for a specific account
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.AccountBalanceResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - JWT: []
      summary: Get account balance
      tags:
      - account
  /api/v1/user:
    post:
      parameters:
      - description: item to create
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.model'
      tags:
      - user
  /api/v1/user/{id}:
    get:
      parameters:
      - description: uuid of item
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.model'
      tags:
      - user
    patch:
      parameters:
      - description: uuid of item
        in: path
        name: id
        required: true
        type: string
      - description: update body
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/user.model'
      responses:
        "200":
          description: ok
          schema:
            type: string
      tags:
      - user
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: JWT token and user info
          schema:
            $ref: '#/definitions/user.LoginUserResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - user
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
